apiVersion: apps/v1
kind: Deployment
metadata: 
  name: contaquedeployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: contaqueapp
  template:
    metadata: 
      name: contaqueapppod
      labels:
        app: contaqueapp
    spec:
      containers:
      - name: contaquecontainer
        image: ganesh1891/mydotnet-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: contaqueservice
spec:
  type: LoadBalancer
  selector:
    app: contaqueapp
  ports:  
    - port: 80
      targetPort: 80
